name: Build Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pyinstaller pillow pytz

    - name: Build executable
      run: |
        pyinstaller --onedir --noconsole --icon=file_renamer_icon.ico --add-data "file_renamer_icon.ico;." --hidden-import=PIL --hidden-import=PIL.Image --hidden-import=PIL._imaging --hidden-import=PIL.ExifTags --hidden-import=tkinter --hidden-import=pytz rename_files.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rename_files_executable
        path: dist/
        retention-days: 7
