name: Update GitHub Pages with Latest Release

on:
  release:
    types: [published]

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Fetch the latest release
      run: |
        LATEST_RELEASE=$(gh release view --json assets,url --jq '.url')
        echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

    - name: Generate updated index.html
      run: |
        echo '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>File Renamer</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    margin: 0;
                    padding: 0;
                    text-align: center;
                    background-color: #f9f9f9;
                    color: #333;
                }
                header {
                    background-color: #4CAF50;
                    color: white;
                    padding: 1rem;
                }
                main {
                    padding: 2rem;
                }
                a.download-btn {
                    display: inline-block;
                    margin-top: 20px;
                    padding: 10px 20px;
                    color: white;
                    background-color: #007BFF;
                    text-decoration: none;
                    border-radius: 5px;
                }
                a.download-btn:hover {
                    background-color: #0056b3;
                }
            </style>
        </head>
        <body>
            <header>
                <h1>File Renamer</h1>
            </header>
            <main>
                <p>Welcome to the official page for <strong>File Renamer</strong>. Simplify file renaming with powerful features like metadata-based sorting and intuitive GUI support.</p>
                <h2>Download</h2>
                <p>Click the button below to download the latest version:</p>
                <a class="download-btn" href="'$LATEST_RELEASE'">Download File Renamer</a>
                <h2>Features</h2>
                <ul>
                    <li>Renames files based on metadata like date taken.</li>
                    <li>Supports multiple file formats, including images and videos.</li>
                    <li>Provides fallback options for missing metadata.</li>
                </ul>
                <h2>Need Help?</h2>
                <p>For more information or to report bugs, visit the <a href="https://github.com/dcwelch/file_renamer/issues">GitHub Issues page</a>.</p>
            </main>
        </body>
        </html>' > index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
