name: Build, Update Webpage, and Deploy

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-executable:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        $piexif_path = python -c "import piexif; import os; print(os.path.dirname(piexif.__file__))"
        pyinstaller --clean --noconfirm --noconsole --icon=file_renamer_icon.ico --add-data "file_renamer_icon.ico;." --add-data "$piexif_path;piexif" --hidden-import=pillow_heif --hidden-import=pytz.zoneinfo --hidden-import=piexif --collect-all pillow_heif --collect-all piexif --exclude-module numpy --exclude-module mkl --exclude-module tcl --exclude-module tbb --exclude-module pywin32 --exclude-module psutil --log-level=DEBUG rename_files.py
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rename_files_executable
        path: dist/

  update-gh-pages:
    runs-on: ubuntu-latest
    needs: build-executable
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch latest release URL
      id: fetch-latest-release
      run: |
        LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/dcwelch/file_renamer/releases/latest | jq -r '.assets[] | select(.name | endswith(".zip")).browser_download_url')
        echo "LATEST_RELEASE_URL=${LATEST_RELEASE_URL}" >> $GITHUB_ENV

    - name: Update webpage
      run: |
        mkdir gh-pages
        echo '<!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>File Renamer</title>
          <link rel="icon" href="https://raw.githubusercontent.com/DCWelch/file_renamer/refs/heads/main/file_renamer/file_renamer_icon.ico" type="image/x-icon">
          <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
          <style>
            body {
              font-family: "Open Sans", sans-serif;
              margin: 0;
              padding: 0;
              background-color: #f9f9f9;
              color: #333;
              text-align: center;
            }
            main {
              max-width: 700px;
              margin: 0 auto;
              padding: 2rem;
            }
            .logo {
              width: 64px;
              height: 64px;
              margin-top: 2rem;
            }
            h1 {
              font-size: 2rem;
              margin: 1rem 0;
            }
            p, ul {
              font-size: 1rem;
              line-height: 1.6;
            }
            a.download-btn {
              display: inline-block;
              margin: 1rem 0;
              padding: 10px 20px;
              color: white;
              background-color: #007BFF;
              text-decoration: none;
              border-radius: 5px;
            }
            a.download-btn:hover {
              background-color: #0056b3;
            }
            ul {
              list-style-position: inside;
              padding-left: 0;
              text-align: left;
              margin: 1rem auto;
              display: inline-block;
            }
          </style>
        </head>
        <body>
          <main>
            <img src="https://raw.githubusercontent.com/DCWelch/file_renamer/refs/heads/main/file_renamer/file_renamer_icon.ico" alt="File Renamer logo" class="logo">
            <h1>File Renamer</h1>
            <p>This is the landing page for <strong>DCWelch&apos;s File Renamer</strong> tool, designed to rename vacation photos to a simple date taken-based format at the click of a button. For more information, please visit the <a href="https://github.com/DCWelch/file_renamer">GitHub Repository</a>.</p>
            <h2>Download</h2>
            <p>Click the button below to download the latest version:</p>
            <a class="download-btn" href="'$LATEST_RELEASE_URL'">Download File Renamer</a>
            <h2>Features</h2>
            <ul>
              <li>Renames files based on metadata like date taken.</li>
              <li>Supports multiple file formats, including images and videos.</li>
              <li>Provides fallback options for missing metadata.</li>
            </ul>
            <h2>Need Help?</h2>
            <p>For more information or to report bugs, visit the <a href="https://github.com/dcwelch/file_renamer/issues">GitHub Issues page</a>.</p>
          </main>
        </body>
        </html>' > gh-pages/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
