name: Build, Update Webpage, and Deploy

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-executable:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    # Step 4: Build the Windows executable
    - name: Build executable
      run: |
        pyinstaller --noconfirm --noconsole --icon=file_renamer_icon.ico --add-data "file_renamer_icon.ico;." --hidden-import=pillow_heif --hidden-import=pytz.zoneinfo --exclude-module numpy --exclude-module mkl --exclude-module tcl --exclude-module tbb --exclude-module pywin32 --exclude-module psutil rename_files.py

    # Step 5: Upload as artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rename_files_executable
        path: dist/

  update-gh-pages:
    runs-on: ubuntu-latest
    needs: build-executable
    if: github.event_name == 'push'

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Update webpage content (no executable update)
    - name: Update webpage
      run: |
        mkdir gh-pages
        echo '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>File Renamer</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    margin: 0;
                    padding: 0;
                    text-align: center;
                    background-color: #f9f9f9;
                    color: #333;
                }
                header {
                    background-color: #4CAF50;
                    color: white;
                    padding: 1rem;
                }
                main {
                    padding: 2rem;
                }
                a.download-btn {
                    display: inline-block;
                    margin-top: 20px;
                    padding: 10px 20px;
                    color: white;
                    background-color: #007BFF;
                    text-decoration: none;
                    border-radius: 5px;
                }
                a.download-btn:hover {
                    background-color: #0056b3;
                }
            </style>
        </head>
        <body>
            <header>
                <h1>File Renamer</h1>
            </header>
            <main>
                <p>Welcome to the official page for <strong>File Renamer</strong>. Simplify file renaming with powerful features like metadata-based sorting and intuitive GUI support.</p>
                <h2>Download</h2>
                <p>The latest release is available below:</p>
                <a class="download-btn" href="rename_files.exe">Download File Renamer</a>
                <h2>Features</h2>
                <ul>
                    <li>Renames files based on metadata like date taken.</li>
                    <li>Supports multiple file formats, including images and videos.</li>
                    <li>Provides fallback options for missing metadata.</li>
                </ul>
                <h2>Need Help?</h2>
                <p>For more information or to report bugs, visit the <a href="https://github.com/dcwelch/file_renamer/issues">GitHub Issues page</a>.</p>
            </main>
        </body>
        </html>' > gh-pages/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages

  update-gh-pages-release:
    runs-on: ubuntu-latest
    needs: build-executable
    if: github.event_name == 'release'

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Update webpage content with release executable
    - name: Update webpage with release executable
      run: |
        mkdir gh-pages
        cp dist/rename_files.exe gh-pages/
        echo '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>File Renamer</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    margin: 0;
                    padding: 0;
                    text-align: center;
                    background-color: #f9f9f9;
                    color: #333;
                }
                header {
                    background-color: #4CAF50;
                    color: white;
                    padding: 1rem;
                }
                main {
                    padding: 2rem;
                }
                a.download-btn {
                    display: inline-block;
                    margin-top: 20px;
                    padding: 10px 20px;
                    color: white;
                    background-color: #007BFF;
                    text-decoration: none;
                    border-radius: 5px;
                }
                a.download-btn:hover {
                    background-color: #0056b3;
                }
            </style>
        </head>
        <body>
            <header>
                <h1>File Renamer</h1>
            </header>
            <main>
                <p>Welcome to the official page for <strong>File Renamer</strong>. Simplify file renaming with powerful features like metadata-based sorting and intuitive GUI support.</p>
                <h2>Download</h2>
                <p>Click the button below to download the latest version:</p>
                <a class="download-btn" href="rename_files.exe">Download File Renamer</a>
                <h2>Features</h2>
                <ul>
                    <li>Renames files based on metadata like date taken.</li>
                    <li>Supports multiple file formats, including images and videos.</li>
                    <li>Provides fallback options for missing metadata.</li>
                </ul>
                <h2>Need Help?</h2>
                <p>For more information or to report bugs, visit the <a href="https://github.com/dcwelch/file_renamer/issues">GitHub Issues page</a>.</p>
            </main>
        </body>
        </html>' > gh-pages/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
